-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 12:07:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tranferencia-IBAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tranferencia-IBAN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `Iban` CHAR(25) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`levantamento-sem-cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`levantamento-sem-cartao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod-secreto` TINYINT(3) NOT NULL,
  `quantia` FLOAT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_levantamento-sem-cartao_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_levantamento-sem-cartao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transferencia-express`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transferencia-express` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(13) NOT NULL,
  `Ordenante` VARCHAR(45) NOT NULL,
  `mensagem` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento-estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento-estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento-referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento-referencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transferencia-via-express`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transferencia-via-express` (
  `transferencia-express_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`transferencia-express_id`, `usuario_id`),
  INDEX `fk_transferencia-express_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_transferencia-express_has_usuario_transferencia-express1_idx` (`transferencia-express_id` ASC) VISIBLE,
  CONSTRAINT `fk_transferencia-express_has_usuario_transferencia-express1`
    FOREIGN KEY (`transferencia-express_id`)
    REFERENCES `mydb`.`transferencia-express` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferencia-express_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transferencia-por-iban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transferencia-por-iban` (
  `usuario_id` INT NOT NULL,
  `tranferencia-IBAN_id` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`usuario_id`, `tranferencia-IBAN_id`),
  INDEX `fk_usuario_has_tranferencia-IBAN_tranferencia-IBAN1_idx` (`tranferencia-IBAN_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_tranferencia-IBAN_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_tranferencia-IBAN_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_tranferencia-IBAN_tranferencia-IBAN1`
    FOREIGN KEY (`tranferencia-IBAN_id`)
    REFERENCES `mydb`.`tranferencia-IBAN` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario-paga-ao-estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario-paga-ao-estado` (
  `usuario_id` INT NOT NULL,
  `pagamento-estado_id` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`usuario_id`, `pagamento-estado_id`),
  INDEX `fk_usuario_has_pagamento-estado_pagamento-estado1_idx` (`pagamento-estado_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_pagamento-estado_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_pagamento-estado_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_pagamento-estado_pagamento-estado1`
    FOREIGN KEY (`pagamento-estado_id`)
    REFERENCES `mydb`.`pagamento-estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario-paga-por-referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario-paga-por-referencia` (
  `usuario_id` INT NOT NULL,
  `pagamento-referencia_id` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`usuario_id`, `pagamento-referencia_id`),
  INDEX `fk_usuario_has_pagamento-referencia_pagamento-referencia1_idx` (`pagamento-referencia_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_pagamento-referencia_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_pagamento-referencia_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_pagamento-referencia_pagamento-referencia1`
    FOREIGN KEY (`pagamento-referencia_id`)
    REFERENCES `mydb`.`pagamento-referencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
